teleport:
  countdown: 5
  allowed-walk-range: 0
  safe-teleport: false
request:
  expiration-time: 120
  cooldown: 30
  daily-limit: -1
blacklisted-worlds:
  enabled: true
  worlds:
    - world_nether
    - world_the_end
gui:
  enabled: true
  command-enabled: false
override-essentials: true
worlds:
  world: "Overworld"
  world_nether: "Nether"
  world_the_end: "End"
